version: "3.7"

services:
  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: codingbee
      POSTGRES_PASSWORD: codingbee_pass
    ports:
      - "2345:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
    driver: local
